apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
  namespace: my-namespace
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db
